// Copyright 2026 The DataHub Project Authors
// SPDX-License-Identifier: Apache-2.0

package importtool

import (
	"bytes"
	"fmt"
)

// WriteImportReadme produces the IMPORT_README.md content.
func WriteImportReadme(numImports int, vars []Variable) []byte {
	var b bytes.Buffer

	fmt.Fprintf(&b, "# Import README\n\n")
	fmt.Fprintf(&b, "This directory was generated by `datahub-tf-import enumerate`.\n")
	fmt.Fprintf(&b, "It contains Terraform configuration to adopt %d existing DataHub resources into state.\n\n", numImports)

	fmt.Fprintf(&b, "## Files\n\n")
	fmt.Fprintf(&b, "- `import.tf` -- `import {}` blocks and provider configuration\n")
	fmt.Fprintf(&b, "- `generated.tf` -- resource configuration generated by `terraform plan -generate-config-out`\n")
	if len(vars) > 0 {
		fmt.Fprintf(&b, "- `variables.tf` -- sensitive variable declarations for WriteOnly attributes\n")
		fmt.Fprintf(&b, "- `terraform.tfvars` -- **you must create this** (see below); it is gitignored\n")
	}
	fmt.Fprintf(&b, "\n")

	if len(vars) > 0 {
		fmt.Fprintf(&b, "## Step 1 -- Fill in sensitive values\n\n")
		fmt.Fprintf(&b, "Create `terraform.tfvars` (it is gitignored and must NOT be committed):\n\n")
		fmt.Fprintf(&b, "```hcl\n")
		for _, v := range vars {
			fmt.Fprintf(&b, "%s = \"<fill in>\"\n", v.Name)
		}
		fmt.Fprintf(&b, "```\n\n")
		fmt.Fprintf(&b, "## Step 2 -- Add connection platform blocks\n\n")
		fmt.Fprintf(&b, "Open `generated.tf` and fill in the commented platform block stubs for any\n")
		fmt.Fprintf(&b, "`datahub_connection` resources. The config blob is encrypted at rest and\n")
		fmt.Fprintf(&b, "cannot be retrieved from the API -- you must re-supply the credentials.\n\n")
		fmt.Fprintf(&b, "## Step 3 -- Verify\n\n")
	} else {
		fmt.Fprintf(&b, "## Step 1 -- Add connection platform blocks\n\n")
		fmt.Fprintf(&b, "Open `generated.tf` and fill in the commented platform block stubs for any\n")
		fmt.Fprintf(&b, "`datahub_connection` resources.\n\n")
		fmt.Fprintf(&b, "## Step 2 -- Verify\n\n")
	}

	fmt.Fprintf(&b, "```\n")
	fmt.Fprintf(&b, "terraform plan\n")
	fmt.Fprintf(&b, "```\n\n")
	fmt.Fprintf(&b, "The plan should show no changes (all resources imported, config matches state).\n\n")

	lastStep := 2
	if len(vars) > 0 {
		lastStep = 3
	}
	fmt.Fprintf(&b, "## Step %d -- Apply (adopts state)\n\n", lastStep)
	fmt.Fprintf(&b, "```\n")
	fmt.Fprintf(&b, "terraform apply\n")
	fmt.Fprintf(&b, "```\n\n")
	fmt.Fprintf(&b, "`terraform apply` with no pending changes is a no-op -- it adopts the imported\n")
	fmt.Fprintf(&b, "state without modifying any DataHub resources.\n\n")
	fmt.Fprintf(&b, "## Note on eventual consistency\n\n")
	fmt.Fprintf(&b, "DataHub's search index (OpenSearch) is eventually consistent. If the enumeration\n")
	fmt.Fprintf(&b, "ran immediately after resources were created, some URNs may have been missed.\n")
	fmt.Fprintf(&b, "Re-run `datahub-tf-import enumerate` to pick up any stragglers.\n")

	return b.Bytes()
}
