# Copyright 2026 The DataHub Project Authors
# SPDX-License-Identifier: Apache-2.0
#
# Data quality assertions (DataHub Observe) for ISO 20022 PostgreSQL datasets.
#
# This file manages 5 assertion types across 26 representative ISO 20022 message tables:
#   - datahub_schema_assertion    : EXACT_MATCH schema stability guard (1 per table, ACTIVE)
#   - datahub_volume_assertion    : minimum row count thresholds (ACTIVE, profile-backed)
#   - datahub_field_assertion     : NULL_COUNT=0 on mandatory identifier fields (ACTIVE, profile-backed)
#   - datahub_sql_assertion       : IS NULL violation counts on key columns (PASSIVE, DB-native)
#   - datahub_freshness_assertion : data must refresh within 24h (1 per table, ACTIVE, audit-log)
#
# The .iso-cache/assertions_config.json file is generated by:
#   make iso-assertions-config   (python3 scripts/iso20022/generate_assertions_config.py)
# It is a generated artifact in the gitignored .iso-cache/ directory (like
# .fibo-cache/fibo.json), NOT committed. When it is absent - a fresh checkout
# that has not run the build - the fileexists guard yields an empty table set
# and no assertions are planned, matching the FIBO cache behaviour in main.tf.

locals {
  _assertions_path = "${path.module}/.iso-cache/assertions_config.json"
  _assertions      = fileexists(local._assertions_path) ? jsondecode(file(local._assertions_path)) : { tables = [] }

  # Keyed by the short identifier (e.g. "pacs-008")
  dq_tables = { for t in local._assertions.tables : t.key => t }

  # Tables that have a volume threshold defined (all 26 in this config)
  dq_volume_tables = { for k, v in local.dq_tables : k => v if v.volume != null }

  # Shared schedule: evaluate daily at 06:00 UTC
  dq_cron     = "0 6 * * *"
  dq_timezone = "UTC"

  # Flatten field rules: "{table-key}_{rule-id}" -> rule object + entity_urn
  dq_field_rules = merge([
    for tk, tv in local.dq_tables : {
      for rule in try(tv.field_rules, []) :
      "${tk}_${rule.id}" => merge(rule, { entity_urn = tv.urn })
    }
  ]...)

  # Flatten SQL rules: "{table-key}_{rule-id}" -> rule object + entity_urn
  dq_sql_rules = merge([
    for tk, tv in local.dq_tables : {
      for rule in try(tv.sql_rules, []) :
      "${tk}_${rule.id}" => merge(rule, { entity_urn = tv.urn })
    }
  ]...)
}

# ---------------------------------------------------------------------------
# Schema stability assertions - one per table, ACTIVE, EXACT_MATCH
#
# Evaluates against DataHub's schema metadata (MySQL-backed, no DB query).
# Fails if any column is added, removed, or has its type changed relative to
# the declared field list. This is the "schema must not change" gate that
# catches accidental schema drift in the ISO 20022 pipeline.
# ---------------------------------------------------------------------------
resource "datahub_schema_assertion" "iso20022" {
  for_each = local.dq_tables

  entity_urn          = each.value.urn
  compatibility       = "EXACT_MATCH"
  description         = "Schema stability for ${each.value.description}. Fails if columns are added, removed, or retyped."
  fields              = [for f in each.value.schema_fields : { path = f.path, type = f.type }]
  evaluation_cron     = local.dq_cron
  evaluation_timezone = local.dq_timezone
  mode                = "ACTIVE"
  on_success_actions  = ["RESOLVE_INCIDENT"]
  on_failure_actions  = ["RAISE_INCIDENT"]
}

# ---------------------------------------------------------------------------
# Volume assertions - minimum row count per table, ACTIVE
#
# Reads from previously ingested DatasetProfile aspects (no live DB query).
# Thresholds reflect realistic daily volumes for a mid-tier financial
# institution: 50,000 for pacs.008 credit transfers down to 50 for account
# management messages. A volume drop below the threshold indicates a pipeline
# gap and raises an incident.
# ---------------------------------------------------------------------------
resource "datahub_volume_assertion" "iso20022" {
  for_each = local.dq_volume_tables

  entity_urn          = each.value.urn
  volume_type         = "ROW_COUNT_TOTAL"
  operator            = "GREATER_THAN_OR_EQUAL_TO"
  single_value        = tostring(each.value.volume.min_rows)
  description         = "Volume gate for ${each.value.description}: must hold >= ${each.value.volume.min_rows} records. Fewer indicates a pipeline ingestion gap."
  source_type         = "DATAHUB_DATASET_PROFILE"
  evaluation_cron     = local.dq_cron
  evaluation_timezone = local.dq_timezone
  mode                = "ACTIVE"
  on_success_actions  = ["RESOLVE_INCIDENT"]
  on_failure_actions  = ["RAISE_INCIDENT"]
}

# ---------------------------------------------------------------------------
# Field metric assertions - NULL_COUNT = 0 on mandatory identifiers, ACTIVE
#
# Reads from DatasetProfile aspects (no live DB query). Targets the 2-3 most
# critical identifier and amount fields per table: MsgId, NbOfTxs, settlement
# amounts, transaction IDs. A null in these fields indicates a structural
# defect in the upstream ISO 20022 message or parser.
# ---------------------------------------------------------------------------
resource "datahub_field_assertion" "iso20022" {
  for_each = local.dq_field_rules

  entity_urn           = each.value.entity_urn
  field_assertion_type = "FIELD_METRIC"
  field_path           = each.value.field_path
  field_type           = each.value.field_type
  field_native_type    = "text"
  metric               = "NULL_COUNT"
  operator             = "EQUAL_TO"
  single_value         = "0"
  description          = each.value.description
  failure_severity     = "HIGH"
  source_type          = "DATAHUB_DATASET_PROFILE"
  evaluation_cron      = local.dq_cron
  evaluation_timezone  = local.dq_timezone
  mode                 = "ACTIVE"
  on_success_actions   = ["RESOLVE_INCIDENT"]
  on_failure_actions   = ["RAISE_INCIDENT"]
}

# ---------------------------------------------------------------------------
# SQL assertions - IS NULL violation counts, PASSIVE
#
# PASSIVE mode: the assertion rule is registered in DataHub and visible in the
# UI Validations tab, but evaluation requires a live database connection
# (configured via an executor with DB credentials). Use PASSIVE here because
# the demo targets synthetic PostgreSQL datasets with no live instance.
#
# Rules check that critical columns contain no null values. The SQL uses
# double-quoted column names because ISO 20022 field paths contain dots
# (e.g. "FIToFICstmrCdtTrf.GrpHdr.MsgId"), which PostgreSQL requires to be
# double-quoted as identifiers.
# ---------------------------------------------------------------------------
resource "datahub_sql_assertion" "iso20022" {
  for_each = local.dq_sql_rules

  entity_urn          = each.value.entity_urn
  sql_type            = "METRIC"
  statement           = each.value.statement
  operator            = "EQUAL_TO"
  value               = "0"
  description         = each.value.description
  failure_severity    = each.value.severity
  evaluation_cron     = local.dq_cron
  evaluation_timezone = local.dq_timezone
  mode                = "PASSIVE"
  on_success_actions  = ["RESOLVE_INCIDENT"]
  on_failure_actions  = ["RAISE_INCIDENT"]
}

# ---------------------------------------------------------------------------
# Freshness assertions - data must refresh within 24h, one per table, ACTIVE
#
# A freshness assertion answers "has this dataset been updated recently
# enough?" - the classic stale-data guard. ISO 20022 message tables for a
# live financial institution are written continuously, so a 24-hour silence
# means the upstream feed has stalled. source_type DATAHUB_OPERATION derives
# freshness from DataHub Operation aspects (no live DB query). DataHub rejects
# AUDIT_LOG for a platform that has a configured connection (postgres here);
# DATAHUB_OPERATION is the allowed source type for these datasets.
#
# These are the headline DataHub Observe assertion type for "is my pipeline
# still running?" and pair naturally with the volume gate (which catches a
# partial feed) - freshness catches a fully stopped feed.
# ---------------------------------------------------------------------------
resource "datahub_freshness_assertion" "iso20022" {
  for_each = local.dq_tables

  entity_urn              = each.value.urn
  schedule_type           = "FIXED_INTERVAL"
  fixed_interval_unit     = "HOUR"
  fixed_interval_multiple = 24
  description             = "Freshness gate for ${each.value.description}: data must refresh within 24 hours. A longer silence indicates a stalled upstream feed."
  source_type             = "DATAHUB_OPERATION"
  evaluation_cron         = local.dq_cron
  evaluation_timezone     = local.dq_timezone
  mode                    = "ACTIVE"
  on_success_actions      = ["RESOLVE_INCIDENT"]
  on_failure_actions      = ["RAISE_INCIDENT"]
}
