terraform {
  required_version = ">= 1.11"
  required_providers {
    datahub = {
      source  = "datahub-project/datahub"
      version = "0.8.0"
    }
  }
}

provider "datahub" {
  # Credentials from environment variables:
  #   DATAHUB_GMS_URL   - DataHub GMS endpoint (e.g. https://your-instance.acryl.io/gms)
  #   DATAHUB_GMS_TOKEN - personal access token with Manage Domains and
  #                       Manage Glossaries privileges
}

# Read the locally-generated FIBO hierarchy.
# Run `make fibo-data` once before terraform apply to clone the FIBO repo and
# produce this file. The file is gitignored; re-run `make fibo-update` to
# regenerate after a FIBO release or script change.
#
# License: FIBO is MIT-licensed by the EDM Council.
#   Copyright (c) 2020 Enterprise Data Management Council
#   https://github.com/edmcouncil/fibo/blob/master/LICENSE
locals {
  _fibo_raw = fileexists("${path.module}/.fibo-cache/fibo.json") ? jsondecode(file("${path.module}/.fibo-cache/fibo.json")) : null

  # True when the cache exists and was generated by the current script version,
  # which adds a 'terms' list to every leaf object.
  _cache_valid = local._fibo_raw != null && can(local._fibo_raw.root.domains[0].modules[0].leaves[0].terms)

  _fibo = local._fibo_raw

  # Domains to exclude (ontology scaffolding -- already filtered by the script,
  # but repeated here for transparency).
  skip_domains = toset(["FND", "BP"])

  # Guard on _cache_valid so that when the cache is missing or stale, all
  # downstream for-each maps are empty and l.terms is never evaluated.
  # terraform_data.fibo_cache_guard then fires the actionable plan error.
  selected_domains = local._cache_valid ? [
    for d in local._fibo.root.domains : d
    if !contains(local.skip_domains, d.code)
    && (length(var.domains_filter) == 0 || contains(var.domains_filter, d.code))
  ] : []

  # Level 1: top-level FIBO domains -- exclude domains where every class across
  # every leaf is deprecated or provisional (e.g. ACTUS, MD).
  fibo_domains = {
    for d in local.selected_domains : d.id => d
    if anytrue([
      for m in d.modules : anytrue([for l in m.leaves : length(l.terms) > 0])
    ])
  }

  # Level 2: modules -- exclude modules where every leaf has no surviving terms
  # (e.g. BE/Corporations, whose sole leaf is entirely deprecated).
  fibo_modules = merge([
    for d in local.selected_domains : {
      for m in d.modules : "${d.id}/${m.id}" => merge(m, { domain_id = d.id })
      if anytrue([for l in m.leaves : length(l.terms) > 0])
    }
  ]...)

  # Level 3: leaf ontology nodes -- exclude leaves with no surviving terms
  # (all classes deprecated or the whole file is provisional).
  fibo_leaves = merge([
    for d in local.selected_domains : merge([
      for m in d.modules : {
        for l in m.leaves : "${d.id}/${m.id}/${l.id}" => merge(l, {
          domain_id = d.id
          module_id = m.id
        })
        if length(l.terms) > 0
      }
    ]...)
  ]...)

  # ---------------------------------------------------------------------------
  # Glossary locals -- mirror the domain hierarchy as glossary nodes, with
  # owl:Class definitions from each leaf ontology as glossary terms.
  # ---------------------------------------------------------------------------

  # Glossary domain nodes -- only domains that have at least one non-empty leaf
  # after deprecated and provisional filtering. Domains where every class is
  # deprecated or provisional (e.g. ACTUS, MD) produce 0 terms and are omitted.
  fibo_glossary_domains = {
    for d in local.selected_domains : d.id => d
    if anytrue([
      for m in d.modules : anytrue([for l in m.leaves : length(l.terms) > 0])
    ])
  }

  # Glossary module nodes -- only modules that have at least one leaf with terms.
  # Entirely-deprecated modules (e.g. BE/Corporations) are omitted.
  fibo_glossary_modules = merge([
    for d in local.selected_domains : {
      for m in d.modules : "${d.id}/${m.id}" => merge(m, { domain_id = d.id })
      if anytrue([for l in m.leaves : length(l.terms) > 0])
    }
  ]...)

  # Glossary leaf nodes -- only leaves that have at least one term. Leaves where
  # all classes are deprecated (e.g. BE/Corporations/Corporations.rdf) are omitted.
  fibo_glossary_leaves = merge([
    for d in local.selected_domains : merge([
      for m in d.modules : {
        for l in m.leaves : "${d.id}/${m.id}/${l.id}" => merge(l, {
          domain_id = d.id
          module_id = m.id
        })
        if length(l.terms) > 0
      }
    ]...)
  ]...)

  # Glossary terms -- one per owl:Class extracted from each leaf .rdf file.
  # Keyed by "{domain_id}/{module_id}/{leaf_id}/{term_id}" for uniqueness.
  fibo_terms = var.create_glossary ? merge([
    for d in local.selected_domains : merge([
      for m in d.modules : merge([
        for l in m.leaves : {
          for t in l.terms : "${d.id}/${m.id}/${l.id}/${t.id}" => merge(t, {
            domain_id = d.id
            module_id = m.id
            leaf_id   = l.id
          })
        }
      ]...)
    ]...)
  ]...) : {}
}

# Fail-fast guard: fails during plan with a clear message if the FIBO cache is
# missing or stale. Run: make fibo-update
resource "terraform_data" "fibo_cache_guard" {
  lifecycle {
    precondition {
      condition     = local._cache_valid
      error_message = "FIBO cache is missing or stale. Run: make fibo-update"
    }
  }
}

# Optional single root node above all domain nodes.
resource "datahub_domain" "fibo_root" {
  count       = var.create_root_node ? 1 : 0
  domain_id   = "tf-example-fibo-root"
  name        = try(local._fibo.root.name, "")
  description = try(local._fibo.root.description, "")
}

# Level 1 -- top-level FIBO domain nodes (e.g. Securities, Derivatives).
# When create_root_node is true, these are nested under the root; otherwise
# they are root-level DataHub domains.
resource "datahub_domain" "fibo_domain" {
  for_each      = local.fibo_domains
  domain_id     = "tf-example-fibo-${each.value.id}"
  name          = each.value.name
  description   = each.value.description
  parent_domain = var.create_root_node ? datahub_domain.fibo_root[0].urn : null
}

# Level 2 -- module nodes nested under their domain.
# The parent_domain reference gives Terraform the dependency edge so domains
# are created before modules and destroyed after them.
resource "datahub_domain" "fibo_module" {
  for_each      = local.fibo_modules
  domain_id     = "tf-example-fibo-${each.value.domain_id}-${each.value.id}"
  name          = each.value.name
  description   = each.value.description
  parent_domain = datahub_domain.fibo_domain[each.value.domain_id].urn
}

# Level 3 -- leaf ontology nodes nested under their module.
resource "datahub_domain" "fibo_leaf" {
  for_each      = local.fibo_leaves
  domain_id     = "tf-example-fibo-${each.value.domain_id}-${each.value.module_id}-${each.value.id}"
  name          = each.value.name
  description   = each.value.description
  parent_domain = datahub_domain.fibo_module["${each.value.domain_id}/${each.value.module_id}"].urn
}

# =============================================================================
# Glossary hierarchy
#
# Mirrors the domain hierarchy as a Business Glossary. Each leaf ontology
# contributes a glossary node; each owl:Class defined in that ontology becomes
# a glossary term nested beneath it.
#
# The glossary node IDs use the "g" infix to distinguish them from the domain
# IDs above (e.g. "tf-example-fibo-g-sec-debt-bonds" vs
# "tf-example-fibo-sec-debt-bonds").
#
# Destroy ordering is maintained by parent_node = <resource>.urn references,
# which give Terraform the dependency edges to destroy terms before leaf nodes,
# leaf nodes before module nodes, and so on. DataHub has no server-side child
# guard for glossary deletes, so these edges are the only ordering guarantee.
# =============================================================================

# Optional root glossary node (created when both create_glossary and
# create_root_node are true, mirroring datahub_domain.fibo_root).
resource "datahub_glossary_node" "fibo_glossary_root" {
  count       = var.create_glossary && var.create_root_node ? 1 : 0
  node_id     = "tf-example-fibo-g-root"
  name        = try(local._fibo.root.name, "")
  description = try(local._fibo.root.description, "")
}

# Level 1 glossary nodes -- one per top-level FIBO domain.
resource "datahub_glossary_node" "fibo_glossary_domain" {
  for_each    = var.create_glossary ? local.fibo_glossary_domains : {}
  node_id     = "tf-example-fibo-g-${each.value.id}"
  name        = each.value.name
  description = each.value.description
  parent_node = var.create_root_node ? datahub_glossary_node.fibo_glossary_root[0].urn : null
}

# Level 2 glossary nodes -- one per FIBO module, nested under its domain.
resource "datahub_glossary_node" "fibo_glossary_module" {
  for_each    = var.create_glossary ? local.fibo_glossary_modules : {}
  node_id     = "tf-example-fibo-g-${each.value.domain_id}-${each.value.id}"
  name        = each.value.name
  description = each.value.description
  parent_node = datahub_glossary_node.fibo_glossary_domain[each.value.domain_id].urn
}

# Level 3 glossary nodes -- one per FIBO leaf ontology, nested under its module.
resource "datahub_glossary_node" "fibo_glossary_leaf" {
  for_each    = var.create_glossary ? local.fibo_glossary_leaves : {}
  node_id     = "tf-example-fibo-g-${each.value.domain_id}-${each.value.module_id}-${each.value.id}"
  name        = each.value.name
  description = each.value.description
  parent_node = datahub_glossary_node.fibo_glossary_module["${each.value.domain_id}/${each.value.module_id}"].urn
}

# Glossary terms -- one per owl:Class extracted from each leaf ontology file.
# The term_id is pre-computed by the Python script and is guaranteed to be
# <= 56 characters (DataHub GlossaryTermUrn key limit).
#
# Each term is associated with its top-level FIBO domain (e.g. all SEC terms
# are linked to the Securities domain). This makes the domain visible on the
# term's DataHub page and allows users to filter glossary terms by domain.
resource "datahub_glossary_term" "fibo_term" {
  for_each    = local.fibo_terms
  term_id     = each.value.id
  name        = each.value.name
  description = each.value.definition
  parent_node = datahub_glossary_node.fibo_glossary_leaf["${each.value.domain_id}/${each.value.module_id}/${each.value.leaf_id}"].urn
  domain      = datahub_domain.fibo_domain[each.value.domain_id].urn
}
