// Copyright 2026 The DataHub Project Authors
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
)

// nonNativeAssertionError reports whether an assertion's source means it must
// not be managed by Terraform, returning a diagnostic to surface to the user.
//
// DataHub stamps every assertion with a source: NATIVE (authored as a managed
// monitor), EXTERNAL (reported by an ingestion source, e.g. dbt or Great
// Expectations tests), or INFERRED (DataHub smart/AI monitoring). Only NATIVE
// assertions are author-as-code; EXTERNAL and INFERRED are owned and
// regenerated by the system that produces them, so managing them in Terraform
// would fight that system. The monitor-assertion enumerators already exclude
// them from extraction; this guard additionally blocks a direct
// `terraform import` of one (the source is checked on read, which runs as part
// of ImportState).
//
// An empty source (older DataHub entities, or backends that do not report it)
// is allowed through so the guard never blocks on uncertainty -- only a
// positively non-NATIVE source is refused.
func nonNativeAssertionError(urn, source string) (diag.Diagnostic, bool) {
	if source == "" || source == "NATIVE" {
		return nil, false
	}
	return diag.NewErrorDiagnostic(
		"Assertion is not Terraform-manageable",
		fmt.Sprintf(
			"Assertion %s has source %q. %s assertions are created and maintained by "+
				"the system that produces them -- EXTERNAL by an ingestion source "+
				"(e.g. dbt or Great Expectations tests), INFERRED by DataHub smart "+
				"monitoring -- not by Terraform. Importing it would fight that system. "+
				"Only NATIVE (author-as-code) assertions can be managed by this resource.",
			urn, source, source,
		),
	), true
}
